name: snakemake7
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - conda-forge::openssl>=3.1.0
  - bioconda::snakemake<=8
  - bioconda::snpeff==5.1
  - anaconda::graphviz
  - anaconda::wget
